link:
  home: "https://www.railstutorial.org"
  help: "https://www.railstutorial.org/help"
  book: "https://www.railstutorial.org/book"
  contact: "https://www.railstutorial.org/contact"
  learn_enough: "https://www.learnenough.com/"
  screencast: "https://screencasts.railstutorial.org/"
  rails: "https://rubyonrails.org/"
  author: "https://www.michaelhartl.com/"
  news: "https://news.railstutorial.org/"
image:
  rails:
    width: "200px"
